server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./internet-banking-stat;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
    initialization-mode: embedded

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1024MB

file:
  upload-dir: ./upload
