CREATE TABLE IF NOT EXISTS device_info
(
    id CHAR(36) NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_device_info PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_device_info ON device_info (name);

CREATE TABLE IF NOT EXISTS internet_banking_stat
(
    uid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    year SMALLINT NOT NULL,
    rate DECIMAL NOT NULL,
    CONSTRAINT pk_internet_banking_stat PRIMARY KEY (uid)
);

CREATE INDEX IF NOT EXISTS ix_internet_banking_stat_1 ON internet_banking_stat (year);

CREATE TABLE IF NOT EXISTS internet_banking_stat_detail
(
    uid INTEGER GENERATED BY DEFAULT AS IDENTITY,
    internet_banking_stat_uid INTEGER NOT NULL,
    device_id CHAR(36) NOT NULL,
    rate DECIMAL NOT NULL,
    CONSTRAINT pk_internet_banking_stat_detail PRIMARY KEY (uid),
    CONSTRAINT fk_internet_banking_stat_detail_1 FOREIGN KEY (internet_banking_stat_uid) REFERENCES internet_banking_stat(uid) ON DELETE CASCADE,
    CONSTRAINT fk_internet_banking_stat_detail_2 FOREIGN KEY (device_id) REFERENCES device_info(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_internet_banking_stat_detail_1 ON internet_banking_stat (rate);

